name: Lint

on: [pull_request]

jobs:
  lint:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v1
        with:
          node-version: '14.x'
      - uses: bahmutov/npm-install@v1
      - name: npx eslint $FILES_CHANGED
        run: |
          git fetch origin main
          FILES_CHANGED=$(git diff origin/${{ github.base_ref }}.. --name-only -- "*.ts" "*.tsx" "*.js" "*.jsx")
          echo Will check these files:
          echo $FILES_CHANGED
          echo -----------------------
          npx eslint $FILES_CHANGED || true
